---
version: "2"
prepare:
  fetch:
    - url: https://raw.githubusercontent.com/codeclimate/styleguide/master/ruby/rubocop.yml
      path: base_rubocop.yml
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-67
  fixme:
    enabled: true
    exclude_patterns:
      - config/engines.yml
  markdownlint:
    enabled: true
    checks:
      MD002: # "First header should be a h1 header"
        enabled: false
  shellcheck:
    enabled: true
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
exclude_patterns:
  - .bundle/
  - spec/**/*
  - benchmarks/**/*
